// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: core/proto/gameboy.proto

package gameboy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *LoadGameReq) Reset() {
	*x = LoadGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_gameboy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGameReq) ProtoMessage() {}

func (x *LoadGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_gameboy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGameReq.ProtoReflect.Descriptor instead.
func (*LoadGameReq) Descriptor() ([]byte, []int) {
	return file_core_proto_gameboy_proto_rawDescGZIP(), []int{0}
}

func (x *LoadGameReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type BaseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_gameboy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_gameboy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_core_proto_gameboy_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ButtonEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  int32 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Mode int32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ButtonEvent) Reset() {
	*x = ButtonEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_gameboy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ButtonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonEvent) ProtoMessage() {}

func (x *ButtonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_gameboy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonEvent.ProtoReflect.Descriptor instead.
func (*ButtonEvent) Descriptor() ([]byte, []int) {
	return file_core_proto_gameboy_proto_rawDescGZIP(), []int{2}
}

func (x *ButtonEvent) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ButtonEvent) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type EventToC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`  //1.frame 2.sta
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` //data
}

func (x *EventToC) Reset() {
	*x = EventToC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_proto_gameboy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventToC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventToC) ProtoMessage() {}

func (x *EventToC) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_gameboy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventToC.ProtoReflect.Descriptor instead.
func (*EventToC) Descriptor() ([]byte, []int) {
	return file_core_proto_gameboy_proto_rawDescGZIP(), []int{3}
}

func (x *EventToC) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *EventToC) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_core_proto_gameboy_proto protoreflect.FileDescriptor

var file_core_proto_gameboy_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x62, 0x6f, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0b, 0x4c, 0x6f,
	0x61, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x30, 0x0a,
	0x08, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x33, 0x0a, 0x0b, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x22, 0x34, 0x0a, 0x08, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x43,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x62, 0x6f, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_proto_gameboy_proto_rawDescOnce sync.Once
	file_core_proto_gameboy_proto_rawDescData = file_core_proto_gameboy_proto_rawDesc
)

func file_core_proto_gameboy_proto_rawDescGZIP() []byte {
	file_core_proto_gameboy_proto_rawDescOnce.Do(func() {
		file_core_proto_gameboy_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_proto_gameboy_proto_rawDescData)
	})
	return file_core_proto_gameboy_proto_rawDescData
}

var file_core_proto_gameboy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_proto_gameboy_proto_goTypes = []interface{}{
	(*LoadGameReq)(nil), // 0: LoadGameReq
	(*BaseResp)(nil),    // 1: BaseResp
	(*ButtonEvent)(nil), // 2: ButtonEvent
	(*EventToC)(nil),    // 3: EventToC
}
var file_core_proto_gameboy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_proto_gameboy_proto_init() }
func file_core_proto_gameboy_proto_init() {
	if File_core_proto_gameboy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_proto_gameboy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_gameboy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_gameboy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ButtonEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_proto_gameboy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventToC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_proto_gameboy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_gameboy_proto_goTypes,
		DependencyIndexes: file_core_proto_gameboy_proto_depIdxs,
		MessageInfos:      file_core_proto_gameboy_proto_msgTypes,
	}.Build()
	File_core_proto_gameboy_proto = out.File
	file_core_proto_gameboy_proto_rawDesc = nil
	file_core_proto_gameboy_proto_goTypes = nil
	file_core_proto_gameboy_proto_depIdxs = nil
}
